"""Add rate to trips

Revision ID: 4fd504b7ca8e
Revises: 5e52fc8d627d
Create Date: 2025-11-21 14:55:23.656626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd504b7ca8e'
down_revision: Union[str, Sequence[str], None] = '5e52fc8d627d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'rate')
    # ### end Alembic commands ###
